version: "3"

networks:
  default:
    name: docker-network

volumes:
  wp:
    driver: local
    driver_opts:
      device: /home/seongjki/data/wp
      o: bind
      type: volume
  
  db:
    driver: local
    driver_opts:
      device: /home/seongjki/data/db
      o: bind
      type: volume

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb:inception
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - default
    restart: on-failure

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    image: wordpress:inception
    env_file:
      - .env
    restart: on-failure
    volumes:
      - wp:/var/www/html/
    networks:
      - default
  
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    image: nginx:inception
    restart: on-failure
    volumes:
      - wp:/var/www/html/
    networks:
      - default
    ports:
      - 443:443
